import type { Metadata } from 'next'
import { type ReactNode } from 'react'
import './globals.css'

export const metadata: Metadata = {
  title: 'Legend Mama',
  description: 'Generated by create next app' // TODO: CHANGE THIS!
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): ReactNode {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
