import type { Metadata } from "next";
import { Armata, Mirza, Jacquard_24, VT323 } from "next/font/google";
import "@/styles/globals.css";
import Footer from "@/components/footer";
import * as React from "react";


const armata = Armata({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
  variable: '--font-armata-sans',
});

const mirza = Mirza({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
  variable: '--font-mirza-serif',
});

const jacquard24 = Jacquard_24({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
  variable: '--font-jacquard24-system-ui',
});

const vt323 = VT323({
  weight: '400',
  subsets: ['latin'],
  style: 'normal',
  variable: '--font-vt323-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Help on formatting sidebar and footer: https://codepen.io/tinito/pen/WNXPOKX?editors=1010
export default function RootLayout({authenticated, unauthenticated}: Readonly<{
  authenticated: React.ReactNode;
  unauthenticated: React.ReactNode;
}>) {
  const loggedIn = true;
  return (
    <html lang="en" className={`${armata.variable} ${mirza.variable} ${jacquard24.variable} ${vt323.variable}`}>
    <body>
      <div className="flex flex-col h-screen">
        <div className="flex flex-1 overflow-hidden bg-background-2">
          {loggedIn ? authenticated : unauthenticated}
        </div>
        <Footer/>
      </div>
    </body>
    </html>
  );
}
