import {body, validationResult, matchedData} from 'express-validator';
import {BadRequestError} from "./errorHandlers.js";
import classData from '../data/dnd5e/classes.json' with {type: 'json'};
import raceData from '../data/dnd5e/races.json' with {type: 'json'};
import alignmentData from '../data/dnd5e/alignments.json' with {type: 'json'};


const classes = Object.keys(classData);
const races = Object.keys(raceData);
const alignments = Object.keys(alignmentData);

/**
 * Entry point for validation. Takes in validation rules for route customization.
 * https://dev.to/nedsoft/a-clean-approach-to-using-express-validator-8go
 */
export const validate = (req, res, next) => {
    req.body = matchedData(req, { locations: ['body'], onlyValidData: true });

    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        console.log(errors.array());
        throw new BadRequestError(errors.array());
    }
    next();
}

/**
 * Character Details Validation Rules
 * Validation and sanitization for CharacterDetails object.
 */
export const characterDetailsValidationRules = () => {
    return [
        // Validating and sanitizing the string attributes
        body('name').optional().isString().trim(),
        body('race').optional().isIn(races),
        body('class').optional().isIn(classes),
        body('worldview').isString().trim(),
        body('backstory').optional().isString().trim(),

        // Validating and sanitizing the array attributes
        body('ethicalTraits').isArray({ min: 1 }),
        body('ethicalTraits.*').trim(),
        body('quirks').optional().isArray(),
        body('quirks.*').isString().trim(),
        body('motivations').isArray({ min: 1 }),
        body('motivations.*').isString().trim(),
        body('fears').isArray({ min: 1 }),
        body('fears.*').isString().trim(),
        body('likes').optional().isArray(),
        body('likes.*').isString().trim(),
        body('dislikes').optional().isArray(),
        body('dislikes.*').isString().trim(),

        // Validating and sanitizing the object attributes
        body("personalityTraits.extroversion").isString().trim(),
        body("personalityTraits.agreeableness").isString().trim(),
        body("personalityTraits.conscientiousness").isString().trim(),
        body("personalityTraits.neuroticism").isString().trim(),
        body("personalityTraits.openness").isString().trim(),
    ];
};

/**
 * Generated Character Validation Rules
 * Validation and sanitization for GeneratedCharacter object.
 */
export const generatedCharacterValidationRules = () => {
    return [
        // Validating and sanitizing the string attributes
        body('name').isString().trim(),
        body('race').isIn(races),
        body('class').isIn(classes),
        body('alignment').isIn(alignments),
        body('ideal').isString().trim(),
        body('bond').isString().trim(),
        body('flaw').isString().trim(),
        body('backstory').isString().trim(),

        // Validating and sanitizing the array attributes
        body('toolProficiency').isArray(),
        body('toolProficiency.*').isString().trim(),
        body('languages').isArray(),
        body('languages.*').isString().trim(),
        body('skillProficiency').isArray(),
        body('skillProficiency.*').isString().trim(),
        body('personalityTraits').isArray({ min: 2, max: 2 }),
        body('personalityTraits.*').isString().trim(),
        body('racialStatBonus').isArray(),
        body('racialStatBonus.*').matches(/^(strength|dexterity|constitution|intelligence|wisdom|charisma)+,\d+$/).withMessage('Must be in the format "ability,bonus"'),

        // Validating and sanitizing the object attributes
        body("background.name").isString().trim(),
        body("background.description").isString().trim(),
        body("background.skillProficiency").isArray({min: 2, max: 2}),
        body('background.skillProficiency.*').isString().trim(),
        body("background.toolProficiency").isArray(),
        body('background.toolProficiency.*').isString().trim(),
        body("background.languages").isArray(),
        body('background.languages.*').trim(),
        body("background.feature").isObject(),
        body('background.feature.*').isString().trim(),
        body("abilityScores.strength").isInt({min: 8}),
        body("abilityScores.dexterity").isInt({min: 8}),
        body("abilityScores.constitution").isInt({min: 8}),
        body("abilityScores.intelligence").isInt({min: 8}),
        body("abilityScores.wisdom").isInt({min: 8}),
        body("abilityScores.charisma").isInt({min: 8}),
    ];
};

/**
 * Character Sheet Validation Rules
 * Validation and sanitization for CharacterSheet object. This set of validation rules assumes that the data provided
 * was generated by the character-sheet route. No 5e checks or calculations are performed here.
 */
export const characterSheetValidationRules = () => {
    return [
        // Validating and sanitizing the string attributes
        body('name').optional().isString().trim(),
        body('race').optional().isIn(races),
        body('class').optional().isIn(classes),
        body('alignment').optional().isIn(alignments),
        body('ideal').optional().isString().trim(),
        body('bond').optional().isString().trim(),
        body('flaw').optional().isString().trim(),
        body('backstory').optional().isString().trim(),

        // Validating and sanitizing integer attributes
        body("level").optional().isInt(),
        body("armorClass").optional().isInt(),
        body("initiative").optional().isInt(),
        body("speed").optional().isInt(),
        body("hitDice").optional().isInt(),
        body("hitPointMax").optional().isInt(),
        body("proficiencyBonus").optional().isInt(),
        body("passivePerception").optional().isInt(),

        // Validating and sanitizing the array attributes
        body('armorProficiency').optional().isArray(),
        body('armorProficiency.*').optional().isString().trim(),
        body('weaponProficiency').optional().isArray(),
        body('weaponProficiency.*').optional().isString().trim(),
        body('toolProficiency').optional().isArray(),
        body('toolProficiency.*').optional().isString().trim(),
        body('languages').optional().isArray(),
        body('languages.*').optional().isString().trim(),
        body('skillProficiency').optional().isArray(),
        body('skillProficiency.*').optional().isString().trim(),
        body('features').optional().isArray(),
        body('features.*').optional().isString().trim(),
        body('personalityTraits').optional().isArray({ min: 2, max: 2 }),
        body('personalityTraits.*').optional().isString().trim(),

        // Validating and sanitizing the object attributes
        // Background
        body("background.name").optional().isString().trim(),
        body("background.description").optional().isString().trim(),
        body("background.feature").optional().isObject(),
        body('background.feature.*').optional().isString().trim(),

        // Ability Scores
        body("abilityScores.strength").optional().isInt({min: 8}),
        body("abilityScores.dexterity").optional().isInt({min: 8}),
        body("abilityScores.constitution").optional().isInt({min: 8}),
        body("abilityScores.intelligence").optional().isInt({min: 8}),
        body("abilityScores.wisdom").optional().isInt({min: 8}),
        body("abilityScores.charisma").optional().isInt({min: 8}),

        // Ability Modifiers
        body("abilityModifiers.strength").optional().isInt(),
        body("abilityModifiers.dexterity").optional().isInt(),
        body("abilityModifiers.constitution").optional().isInt(),
        body("abilityModifiers.intelligence").optional().isInt(),
        body("abilityModifiers.wisdom").optional().isInt(),
        body("abilityModifiers.charisma").optional().isInt(),

        // Saving Throws
        body("savingThrows.strength").optional().isInt(),
        body("savingThrows.dexterity").optional().isInt(),
        body("savingThrows.constitution").optional().isInt(),
        body("savingThrows.intelligence").optional().isInt(),
        body("savingThrows.wisdom").optional().isInt(),
        body("savingThrows.charisma").optional().isInt(),

        // Skills
        body("skills.Athletics").optional().isInt(),
        body("skills.Acrobatics").optional().isInt(),
        body("skills.Sleight of Hand").optional().isInt(),
        body("skills.Stealth").optional().isInt(),
        body("skills.Arcana").optional().isInt(),
        body("skills.History").optional().isInt(),
        body("skills.Investigation").optional().isInt(),
        body("skills.Nature").optional().isInt(),
        body("skills.Religion").optional().isInt(),
        body("skills.Animal Handling").optional().isInt(),
        body("skills.Insight").optional().isInt(),
        body("skills.Medicine").optional().isInt(),
        body("skills.Perception").optional().isInt(),
        body("skills.Survival").optional().isInt(),
        body("skills.Deception").optional().isInt(),
        body("skills.Intimidation").optional().isInt(),
        body("skills.Performance").optional().isInt(),
        body("skills.Persuasion").optional().isInt(),
    ];
};


